swagger: "2.0"
info:
  title: My API
  version: 1.0.0

x-google-backend:
  address: "https://service-2d6b018-his4nkqvfq-an.a.run.app"

paths:
  /:
    get:
      operationId: rootGet
      summary: Root path
      responses:
        "200":
          description: Successful response
  /test:
    get:
      operationId: testGet
      summary: Test path
      responses:
        "200":
          description: Successful response
